#!/usr/bin/env python
from __future__ import division, print_function, absolute_import, \
     unicode_literals
import subprocess
import textwrap

HEADER_TMP_COMMIT_TITLE = "tmp commit"

answer = input("Push ? [y/N]: ")

if answer == "y":
    cmd = ["git", "log", "--grep", HEADER_TMP_COMMIT_TITLE]
    result = subprocess.run(cmd, stdout=subprocess.PIPE, text=True)

    if result.stdout:
        msg = """\

            整理されていないコミットが残っています。
            整理後、再度 push してください。
            Hint:
              commit --amend で直前コミットの修正する
              git rebase -i <hash値> でコミットは融合させる
        """
        print(textwrap.dedent(msg))
else:
    print("Canceld Push.")